### PR TITLE
supplement code for "Out of Memory" issue

### PR DESCRIPTION
**Pull request by nicewook**
issue #130

mnist.test data set is too big for some system so that makes Out of
Memory issue.
Commented code split dataset and predict to avoid "OOM" issue

### CODE REVIEW

**Comment by kkweon** [comment]
Hmm, I believe that will work, but how about we just define a helper function instead of comments?

```python
def evaluate(X_sample, y_sample, batch_size=512):
    """Run a minibatch accuracy op"""
    
    N = X_sample.shape[0]
    correct_sample = 0

    for i in range(0, N, batch_size):
        X_batch = X_sample[i: i + batch_size]
        y_batch = y_sampel[i: i + batch_size]
        N_batch = X_batch.shape[0]

        feed = {
            X: X_batch,
            Y: y_batch
        }

        correct_sample += sess.run(accuracy, feed_dict=feed) * N_batch

    return correct_sample / N
```

then we can run

```python
train_acc = evaluate(mnist.train.images, mnist.train.labels)
test_acc = evaluate(mnist.test.images, mnist.test.labels)
```

**Comment by nicewook** [comment]
@kkweon this one is much better!
just one question. 
I think there is possibility of round issue of calculating correct_sample.
if possible, it would be nice to get the number of correct sample directly

**Comment by nicewook** [comment]
I changed code with advice of @kkweon 
- using evaluate() function

I'm a bit confused of added new commit to this pull request. 
at this moments, the latest commit is added?

**Comment by kkweon** [comment]
@nicewook
Once you create a PR, your branch is connected to this upstream branch.
So, whatever commits you make in your branch will be shown here automatically.
If that's what you mean, yes.

I'm waiting for @hunkim's review: do you think it's okay to merge this?

**Comment by hunkim** [comment]
I read the code, but it seems a bit overkill for the 11-2 basic tutorial
for me, Perhaps, should we make it as an X?

Sung

**Comment by nicewook** [comment]
@kkweon I checked and it works.
@hunkim I see what you mean. you are talking about KISS. 
I think it is also good idea that just comment about OOM issue, and better solution goes to next example code. 
As you said, this is **BASIC tutorial** 

- and... what is X?

**Comment by hunkim** [comment]
X means we make it as an optional. 11-X-cnn-memory.....py

**Comment by nicewook** [comment]
IMO, additional .py could be too much.
1. simple comment about OOM
2. fix using evaluate() function
3. additional tutorial .py

everything could works find. 
my suggestion is simple comment, even best solution is evaluate() function. - coz this is basic tutorial

**Comment by hunkim** [comment]
@kkweon, what do you think?

**Comment by kkweon** [comment]
**I have seen more than 5 people claiming that they have an error like this.**
The problem occurred to those who do not have enough memory in their GPUs and try to put the whole test data set into the memory.

**And, it's also very common (if not always) that people use a mini batch for test runs as well because usually the GPU memory is at most 12gb and it's not enough for real world data**

So, I think it's important to let people know they have to use a mini batch for test runs.
I even sometimes run a mini batch size of 8. Anyway...

So, I agree 
* Rename @nicewook's file to `lab-11-X-mnist_cnn_low_memory.py` because 
    * other MNIST files also have the same problem (using the test dataset as a single batch) and defining  an `evaluate(...)` function only in this file seems inconsistent with others. So, we just keep it as optional for now until we get a better idea lol.
* We still need to leave a comment about the OOM issue in the [lab-11-1-mnist_cnn.py](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-11-1-mnist_cnn.py).
* Just one sentence like "if you have a OOM error, please refer to lab-11-X-..."  will do.

**Comment by hunkim** [comment]
Yep. Go for it.

**Comment by nicewook** [comment]
I think @kkweon shows clear solution. 
I totally agree with it. 

just one question on "lab-11-X-mnist_cnn_low_memory.py" naming
- Do I have to add number on "X", if not "X" is common agreement for something? (out of curiosity)

**Comment by hunkim** [comment]
+1 from me.

**Pull request merged**
