### PR TITLE
JupyterNoterbookVersion

### PR DESCRIPTION
**Pull request by chg0901**

### CODE REVIEW

**Comment by hunkim** [comment]
@kkweon Could you review this? Do I need to install a plug-in?

**Comment by chg0901** [comment]
Sorry, it is just a jupyter notebook file. I install my jupyter notebook(4.2.1) by install Anaconda with python version 3.6. I don't know why it cannot review

**Comment by chg0901** [comment]
@hunkim  I check it again, we can review it

**Comment by kkweon** [comment]
@chg0901  Thanks for your contributions :+1:  But, there are a few thing you should pay attention in order to make this process easier for everyone.
- Please read the [contribution guideline](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/CONTRIBUTING.md) before contributing. You should always read/check if there exists a contributing guideline for any open source project.
- You should write a good commit message. Many people are contributing to this repository and If you don't leave a good commit message, people have to diff every file to see what it have changed
- You should leave a nvbiewer link when you commit a jupyter notebook, so it makes other people review the notebook easily because the github doesn't do a good job in compiling the notebook files.
- One commit for one issue(or one logic)
   - You are sending multiple PRs for the same issue (#149, #150, #151, #152)  (this jupyter commit is okay)
   - It sends notifications to everyone who is watching this repo, and you're spamming.

@hunkim It looks okay to me.
## How to preview Jupyer notebook
1. 
image

2. 
image
 
3. Tada
image

Or you can copy the url and use the [nbviewer](https://nbviewer.jupyter.org/)

**Comment by chg0901** [comment]
@kkweon  Sorry for the spamming.Next time I will pay attention to these problem

**Comment by kkweon** [comment]
Closed due to #162

**Pull request closed without merging**
