### PR TITLE
Update lab-09-3-linear_back_prop.py

### PR DESCRIPTION
**Pull request by GzuPark**
to add the result.
I didn't touch other lines because most of code lines are different with others. Do you have a plan that the files make same structure?

### CODE REVIEW

**Comment by hunkim** [comment]
This code is WIP. Did you spot any bugs here?

**Comment by GzuPark** [comment]
This code works well on Python 3.5.2.

**Comment by hunkim** [comment]
I know it's working, but do you think this code is semantically correct?

**Comment by GzuPark** [comment]
I need time to check it out. Some codes are not common and should compare to other discussions and styles.

**Pull request closed without merging**
