### PR TITLE
change name of W_val and cost_val 

### PR DESCRIPTION
**Pull request by Lewisxyz000**
W_val and cost_val to W_record and cost_record
To understand the purpose of variables easily

### CODE REVIEW

**Comment by Lewisxyz000** [comment]
I did three commits by mistake please understand my mistake...

**Comment by kkweon** [comment]
Wouldnt it better to call W_history, cost_history?
Record is a bit overwhelming. 

Record in Conputer Science has its own meaning as a data structure. 

From the name W_vals, I can tell there are multiple W values stored in this variable.

From W_record, I am not sure...you only get misinformation from this name because this is not a record and you cant tell there are multiple values in it.. 

IMO it is not good. Maybe I'm being too picky.

**Comment by Lewisxyz000** [comment]
Thanks for your comment! your idea is better than my naming idea!
I agree with your objections, thank you.

**Comment by kkweon** [comment]
Could you send a fix please? 
Maybe W_history is good
Thank you!

**Comment by Lewisxyz000** [comment]
Yes, I heard your opinion and sent the request right away!

**Pull request merged**
