### PR TITLE
I have cleaned up the code.

### PR DESCRIPTION
**Pull request by zeran4**
수행시간이 소요되는 sess.run( ) 사용을 줄이기 위해
중복이 되는 호출을 방지하고,
하드 코딩된 W feed값을 feed_W로 분리.

### CODE REVIEW

**Comment by hunkim** [comment]
Looks very good. Thanks!

**Comment by Lay4U** [comment]
E tensorflow/core/client/tensor_c_api.cc:485] Placeholder:0 is both fed and fetched.
Traceback (most recent call last):
  File "/home/lay/Downloads/DeepLearningZeroToAll-master/lab-03-1-minimizing_cost_show_graph.py", line 28, in <module>
    curr_cost, curr_W = sess.run([cost, W], feed_dict={W: feed_W})
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Placeholder:0 is both fed and fetched.

에러나는이유가뭔가요? ㅜㅜ

**Comment by zeran4** [comment]
제 환경에서는 에러가 발생을 안하고 있고, 에러가 나올만한 코드도 아니고요 ㅜㅜ
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by zeran4** [comment]
오류 내용을 보면, feed 한 값에 대한 불필요한 리턴값을 받아와서 발생하는 것 같습니다.

curr_cost, _ = sess.run([cost, W], feed_dict={W: feed_W})
W_val.append(feed_W)

**Comment by zeran4** [comment]
아예, W를 빼면 됩니다.
curr_cost = sess.run(cost, feed_dict={W: feed_W})
W_val.append(feed_W)

**Pull request merged**
