### PR TITLE
Fix to get the correct next close price

### PR DESCRIPTION
**Pull request by jin-chong**
안녕하세요.
말씀하신데로 같은 코드를 사용하는 다른 파일들도 수정하였습니다.
감사합니다.
정진규 드림.

### CODE REVIEW

**Comment by hunkim** [comment]
Wonderful!

**Comment by hunkim** [comment]
Still not too bad? 

image

**Comment by hunkim** [comment]
from lab12-5.
image

**Comment by jin-chong** [comment]
haha, Yes not too bad.
This is good enough to show the start point of how to apply ML to quant.
The prediction looks a bit following real prices once that happened, from
the trader point of view, it wouldn't change financial market. ;)

**Pull request merged**
