### PR TITLE
Added lab-10 codes

### PR DESCRIPTION
**Pull request by togheppi**
PyTorch codes for lab-10-1 ~ lab-10-5 are added.

Thank you.

### CODE REVIEW

**Comment by kkweon** [comment]
Awesome! 
Just a small thing. Could you run pep checks to follow python style guides? In this repo, we are trying to make codes as pythonic as possible.

Please check autopep8 or pep8.
For example, you need a single space after comma.

**Comment by togheppi** [comment]
@kkweon Ok. I' ll run pep check  :)

**Comment by hunkim** [comment]
@togheppi When you are done, please let us know. We are happy to merge this. Thanks!

**Comment by togheppi** [comment]
@hunkim I ran autopep8 check for all codes. Please review and merge this.

Thank you.

**Pull request merged**
