### PR TITLE
several commit in this PR

### PR DESCRIPTION
**Pull request by skyer9**
- modify code for compatability with keras 2.x.
 - change requirement Keras 1.2.2 to 2.0.2.
 - fix Travis CI Build Error

### CODE REVIEW

**Comment by kkweon** [comment]
You can ignore the Travis error because the current Travis script is wrong.
It should be a separate issue anyway.
Basically, `sed` has no effect because all scripts run in isolated environments
So, there are lots of unnecessary steps like plotting, running loop several hundred etc.

TL;DR We need a proper test script but again it should be a separate issue.

**Comment by skyer9** [comment]
Finally, fixed Travis bug.
It is because of bug in tensorflow release version.

**Comment by skyer9** [comment]
I don't know how to separate this PR by two.
What should i do?

**Comment by hunkim** [comment]
Thanks. It's ok for now. Later you can make separate branches.

**Comment by skyer9** [comment]
Ah... i will make some time to learn how to make branching.

**Pull request merged**
