### PR TITLE
error patched : Placeholder:0 is both fed and fetched

### PR DESCRIPTION
**Pull request by zeran4**

### CODE REVIEW

**Comment by zeran4** [comment]
curr_cost, _ = sess.run([cost, W], feed_dict={W: feed_W})

changed to

curr_cost = sess.run(cost, feed_dict={W: feed_W})

**Comment by hunkim** [comment]
Thanks! I think the previous code is OK, but based on your idea, I quickly
changed it. See if it works now.

What is your TF version?

Sung

**Comment by zeran4** [comment]
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.__version__)
1.0.1

**Comment by hunkim** [comment]
New code in the GitHub works?

**Comment by zeran4** [comment]
네, 잘 동작합니다. (TF version : 1.0.1, Python 3.5.2, Anaconda 4.2.0 (64-bit), windows 10)

**Pull request closed without merging**
