### PR TITLE
add ipynb directory

### PR DESCRIPTION
**Pull request by FuZer**
According to #148 #155
Added ipynb directory.
I am currently working on lab-02-1 and lab-02-2 and will complete all tasks in the future.

When finished, please accept full request.

### CODE REVIEW

**Comment by chg0901** [comment]
Dear Fuzer, I also have ipython notebook for other chapters, would you like to modify them and add them into this folder?

**Comment by FuZer** [comment]
Thank you. I will check and modify other chapters. This work will probably end this week.

**Comment by kkweon** [comment]
Cool. Can you leave nbviewer links?

**Comment by chg0901** [comment]
Of course.
This link ([V2](https://github.com/chg0901/TensorflowBasicFromDLZoo/tree/master/V2)) is the version I PR.
In fact, there are other chapters but I didn't modify the file names to be same as the version in this open source project.The link is[TensorflowBasicFromDLZoo](https://github.com/chg0901/TensorflowBasicFromDLZoo)

**Comment by kkweon** [comment]
Since it seems there is no further review, I will merge this

**Pull request merged**
