### PR TITLE
refactor: MinMaxScaler, doc, style

### PR DESCRIPTION
**Pull request by kkweon**
1. MinMaxScaler
    - Reason: vectorized implementation is more efficient
2. Doc change
    - Reason: data file columns are `Open, High, Low, Volume, Close`. In old comments, it was in wrong order `..., Close, Volume`
3. Don't linebreak to follow PEP-8 (Max Char Length 79)
    - it's okay to increase the max char length to 100
    - if we want to follow PEP-8, we have to refactor the code instead of a line break
    - https://www.python.org/dev/peps/pep-0008/#maximum-line-length

### CODE REVIEW

**Comment by hunkim** [comment]
Wonderful!

For PEP8, I am just using `autopep8 . --recursive --in-place --pep8-passes 2000 --verbose`. Should I change the option?

**Comment by hunkim** [comment]
If you are OK, could you also change:

* lab-12-6
* Keras/klab-04-4
* Keras/klab-12-3
* Keras/klab-12-4

for consistency?

Thanks a lot!

**Comment by kkweon** [comment]
Yes. It will be a separate PR though.

The reason max line length 79 is to avoid word wrapping, which is a line break.
But, autoformat will linebreak it because it isn't smart enough to refactor codes.

autopep8 also has the option to change the max line length
`autopep8 --max-line-length 100`
or should be ignored
`autopep8 --ignore E501` E501 is the max line error code

**Comment by hunkim** [comment]
Sounds good. Merged!

**Pull request merged**
