### PR TITLE
Minor first pass consistency fixes.

### PR DESCRIPTION
**Pull request by cynthia**
Changes should be fairly straightforward.

### CODE REVIEW

**Comment by cynthia** [comment]
It seems like the Travis check failing is a red herring.

**Comment by hunkim** [comment]
Thanks! Could you change the data in lab-02-3-linear_regression_tensorflow.org.py?

Since I use [1,2,3], [1,2,3] in many other places.

**Comment by cynthia** [comment]
I've brought this up over a Facebook reply, but I think aggregating the data into a single point would probably make sense. That was a bigger change than I felt comfortable with (it touches more than half of the repository) so I figured that should probably be discussed on a GH issue before I send in something that doesn't align with what you have in mind.

**Comment by cynthia** [comment]
(That's my reasoning for not touching lab-02-3, to touch everything in one go)

**Comment by hunkim** [comment]
I'd like to show the data in one file (page) so that students can see the data anytime they won't. Actually, data consistency is less important here. What do you think?

Would you like to review the lab 9-3, 4,5 (back pro). It needs to be polished.

**Comment by cynthia** [comment]
I left my suggestions in #18 - regarding the review of 9-3, 4, 5 I don't see it in tree, has it not been committed yet?

You can raise a pull request against this repository (I'm not sure if you can do that as yourself though, might be possible by pushing as a branch and creating a PR from that branch) and ask for review through the PR. (If you need help with the logistics, feel free to ask me)

**Comment by hunkim** [comment]
@cynthia I guess they are there. lab-09-3, 4, 5. Thanks!

**Comment by cynthia** [comment]
Sure, can you merge this and track the review issue separately?

**Comment by hunkim** [comment]
"Sure, can you merge this"

I don't think it's a good idea to separate the data part. I want to see them with code in one file/page. As I mentioned, data consistency is less important here.

**Comment by hunkim** [comment]
@cynthia Also note that we will transform all py to Jupiter notebook when code review is done.

**Comment by cynthia** [comment]
This PR doesn't separate the data. That's a separate issue, I've simply synchronizes the inline dataset between two lab projects of the same type.

**Comment by hunkim** [comment]
Aha, in this case, could you change the data in lab-02-3 to
```python
x_train = [1, 2, 3]
y_train = [1, 2, 3]
```

**Comment by cynthia** [comment]
Done.

**Comment by hunkim** [comment]
Thanks! Look forward to more PRs for you.

**Pull request merged**
