### PR TITLE
PyTorch version lab codes 

### PR DESCRIPTION
**Pull request by togheppi**
I added some PyTorch codes based on your TF-Lab codes.

- Tested on torch-0.1.11

I can add rest of lab codes if you don't mind.
Thank you.

### CODE REVIEW

**Comment by togheppi** [comment]
I forgot to mention that I was helped by yunjey's pytorch-tutorial (https://github.com/yunjey/pytorch-tutorial) to write some codes.

Thank you.

**Comment by hunkim** [comment]
I was really looking forward to these. Let me merge first and do review later.

**Comment by hunkim** [comment]
@togheppi It would be wonderful to have more pytourch files including RNN, Seq2Seq. I really appreciate it.

**Comment by hunkim** [comment]
@togheppi For somehow, after merging #89 the directory is gone. Could you please send us PR again? I really appreciate it.

@kkweon Do you think we can just revert?

**Comment by hunkim** [comment]
@togheppi Never mind. I reverted #89, and fixed this problem.

**Pull request merged**
