### PR TITLE
AWS Summit 2017 Demo Codes

### PR DESCRIPTION
**Pull request by sxjscience**
This PR Includes the ipython notebooks and speed comparison scripts in our presentation.

For the speed comparison, I've trained MXNet and Keras using my Titan X for 100 epochs. The time they spent are:
Keras 2.0.3 + TF 1.0.1: 47.30 seconds
MXNet: 3.64 seconds

Also, the notebooks can be previewed in
https://nbviewer.jupyter.org/github/sxjscience/DeepLearningZeroToAll/blob/master/aws-2017-seoul/mxnet-logistic_regression_diabetes.ipynb

https://nbviewer.jupyter.org/github/sxjscience/DeepLearningZeroToAll/blob/master/aws-2017-seoul/mxnet-2hidden_fnn_diabetes.ipynb

https://nbviewer.jupyter.org/github/sxjscience/DeepLearningZeroToAll/blob/master/aws-2017-seoul/mxnet-mnist_deep_cnn.ipynb

https://nbviewer.jupyter.org/github/sxjscience/DeepLearningZeroToAll/blob/master/aws-2017-seoul/mxnet-seq2seq.ipynb

### CODE REVIEW

**Comment by kkweon** [comment]
My desktop was busy, so I had to try on my MBP.
Then, 
```
mxnet.base.MXNetError: [11:32:34] src/operator/rnn.cc:14: RNN is only available for gpu at the moment.
```
Really? mxnet come on..
You should make sure the GPU is available when you go to the summit.

I knew Keras was slow (Resnet was like 10 times slower than mxnet), but by this margin? 
Wow, it's very impressive. I can't wait to try on my desktop.

**Comment by kkweon** [comment]
For future reference
```bash
wget https://raw.githubusercontent.com/sxjscience/DeepLearningZeroToAll/1048e66ad09b1a4a020d801a669876f154876631/aws-2017-seoul/keras_seq2seq_speed.py
wget https://raw.githubusercontent.com/sxjscience/DeepLearningZeroToAll/1048e66ad09b1a4a020d801a669876f154876631/aws-2017-seoul/mxnet_seq2seq_speed.py
```

**Comment by hunkim** [comment]
aws-2017-seoul is not the best directory name for ZeroToAll. Can we just put then in mxnet?

**Comment by kkweon** [comment]
I second that. 
Shouldn't you create a separate repo for this?

**Comment by hunkim** [comment]
@sxjscience I think keeping them here is OK, but just put them in mxnet. It should be fine. Thanks!

**Comment by hunkim** [comment]
Since you put, "AWS Summit 2017 - Seoul: MXNet Logistic Regression Example", I think a seperate repos, or your forked repos

**Comment by kkweon** [comment]
# Summary
* I ran line profilers for each files
* Bye Keras. Hello MXNet

## Keras line profiler
```text
Timer unit: 1e-06 s

Total time: 39.4653 s
File: keras_seq2seq_speed.py
Function: main at line 10

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    10                                           @profile
    11                                           def main():
    12         1            2      2.0      0.0      digit = "0123456789"
    13         1            1      1.0      0.0      alpha = "abcdefghij"
    14                                           
    15         1            4      4.0      0.0      char_set = list(set(digit + alpha))  # id -> char
    16         1            6      6.0      0.0      char_dic = {w: i for i, w in enumerate(char_set)}
    17                                           
    18         1            1      1.0      0.0      data_dim = len(char_set)  # one hot encoding size
    19         1            1      1.0      0.0      seq_length = time_steps = 7
    20         1            1      1.0      0.0      num_classes = len(char_set)
    21                                           
    22                                               # Build training date set
    23         1            1      1.0      0.0      dataX = []
    24         1            1      1.0      0.0      dataY = []
    25                                           
    26      1001          835      0.8      0.0      for i in range(1000):
    27      1000        11579     11.6      0.0          rand_pick = np.random.choice(10, 7)
    28      1000         3758      3.8      0.0          x = [char_dic[digit[c]] for c in rand_pick]
    29      1000         2928      2.9      0.0          y = [char_dic[alpha[c]] for c in rand_pick]
    30      1000          986      1.0      0.0          dataX.append(x)
    31      1000          885      0.9      0.0          dataY.append(y)
    32                                           
    33                                               # One-hot encoding
    34         1          634    634.0      0.0      dataX = np_utils.to_categorical(dataX, num_classes=num_classes)
    35                                               # reshape X to be [samples, time steps, features]
    36         1            9      9.0      0.0      dataX = np.reshape(dataX, (-1, seq_length, data_dim))
    37                                           
    38                                               # One-hot encoding
    39         1          624    624.0      0.0      dataY = np_utils.to_categorical(dataY, num_classes=num_classes)
    40                                               # time steps
    41         1            4      4.0      0.0      dataY = np.reshape(dataY, (-1, seq_length, data_dim))
    42                                           
    43                                           
    44         1           20     20.0      0.0      print('Build model...')
    45         1            1      1.0      0.0      TensorBoard(log_dir='./logs', histogram_freq=1,
    46         1           13     13.0      0.0                  write_graph=True, write_images=False)
    47                                           
    48         1           25     25.0      0.0      model = Sequential()
    49                                               # "Encode" the input sequence using an RNN, producing an output of HIDDEN_SIZE
    50                                               # note: in a situation where your input sequences have a variable length,
    51                                               # use input_shape=(None, nb_feature).
    52         1       503957 503957.0      1.3      model.add(LSTM(32, input_shape=(time_steps, data_dim), return_sequences=False))
    53                                           
    54                                               # For the decoder's input, we repeat the encoded input for each time step
    55         1         3050   3050.0      0.0      model.add(RepeatVector(time_steps))
    56                                               # The decoder RNN could be multiple layers stacked or a single layer
    57                                           
    58         1       200396 200396.0      0.5      model.add(LSTM(32, return_sequences=True))
    59                                           
    60                                               # For each of step of the output sequence, decide which character should
    61                                               # be chosen
    62         1        12939  12939.0      0.0      model.add(TimeDistributed(Dense(data_dim)))
    63         1         4637   4637.0      0.0      model.add(Activation('softmax'))
    64         1            2      2.0      0.0      model.compile(loss='categorical_crossentropy',
    65         1        29022  29022.0      0.1                    optimizer='adam')
    66         1            3      3.0      0.0      begin = time.time()
    67         1     38688978 38688978.0     98.0      model.fit(dataX, dataY, epochs=100, verbose=2)
    68         1            2      2.0      0.0      end = time.time()
    69         1            9      9.0      0.0      print("Total Time Spent: %gs" %(end - begin))
```

## MXNet line profiler
```text
Timer unit: 1e-06 s

Total time: 4.59427 s
File: mxnet_seq2seq_speed.py
Function: main at line 11

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    11                                           @profile
    12                                           def main():
    13         1           56     56.0      0.0    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)  # Config the logging
    14         1            7      7.0      0.0    np.random.seed(777)
    15         1          129    129.0      0.0    mx.random.seed(777)
    16                                           
    17         1            2      2.0      0.0    digit = "0123456789"
    18         1            2      2.0      0.0    alpha = "abcdefghij"
    19                                           
    20         1            5      5.0      0.0    char_set = list(set(digit + alpha))  # id -> char
    21         1            8      8.0      0.0    char_dic = {w: i for i, w in enumerate(char_set)}
    22                                           
    23         1            2      2.0      0.0    data_dim = len(char_set)  # one hot encoding size
    24         1            1      1.0      0.0    seq_length = time_steps = 7
    25         1            1      1.0      0.0    num_classes = len(char_set)
    26         1            1      1.0      0.0    batch_size = 32
    27         1            2      2.0      0.0    seq_num = 1000
    28                                           
    29                                             # Build training date set
    30         1           23     23.0      0.0    dataX = np.empty(shape=(seq_num, seq_length), dtype=np.int)
    31         1            5      5.0      0.0    dataY = np.empty(shape=(seq_num, seq_length), dtype=np.int)
    32                                           
    33      1001         1770      1.8      0.0    for i in range(1000):
    34      1000        13020     13.0      0.3        rand_pick = np.random.choice(10, seq_length)
    35      1000         6155      6.2      0.1        dataX[i, :] = [char_dic[digit[c]] for c in rand_pick]
    36      1000         5046      5.0      0.1        dataY[i, :] = [char_dic[alpha[c]] for c in rand_pick]
    37                                           
    38                                             # Build the symbol
    39         1           54     54.0      0.0    data = mx.sym.var('data')  # Shape: (N, T)
    40         1           11     11.0      0.0    target = mx.sym.var('target')  # Shape: (N, T)
    41         1          106    106.0      0.0    lstm1 = mx.rnn.FusedRNNCell(num_hidden=32, prefix="lstm1_", get_next_state=True)
    42         1           47     47.0      0.0    lstm2 = mx.rnn.FusedRNNCell(num_hidden=32, prefix="lstm2_", get_next_state=False)
    43         1          202    202.0      0.0    data_one_hot = mx.sym.one_hot(data, depth=data_dim)  # Shape: (N, T, C)
    44         1           61     61.0      0.0    data_one_hot = mx.sym.transpose(data_one_hot, axes=(1, 0, 2))  # Shape: (T, N, C)
    45         1          428    428.0      0.0    _, encode_state = lstm1.unroll(length=seq_length, inputs=data_one_hot, layout="TNC")
    46         1            2      2.0      0.0    encode_state_h = encode_state[0]  # Shape: (1, N, C)
    47         1           47     47.0      0.0    encode_state_h = mx.sym.broadcast_to(encode_state_h, shape=(seq_length, 0, 0))  # Shape: (T, N, C)
    48         1          186    186.0      0.0    decode_out, _ = lstm2.unroll(length=seq_length, inputs=encode_state_h, layout="TNC")
    49         1           45     45.0      0.0    decode_out = mx.sym.reshape(decode_out, shape=(-1, 32))
    50         1           40     40.0      0.0    logits = mx.sym.FullyConnected(decode_out, num_hidden=data_dim, name="logits")
    51         1           36     36.0      0.0    logits = mx.sym.reshape(logits, shape=(seq_length, -1, data_dim))
    52         1           35     35.0      0.0    logits = mx.sym.transpose(logits, axes=(1, 0, 2))
    53         1          244    244.0      0.0    loss = mx.sym.mean(-mx.sym.pick(mx.sym.log_softmax(logits), target, axis=-1))
    54         1           28     28.0      0.0    loss = mx.sym.make_loss(loss)
    55                                           
    56                                             # Construct the training and testing modules
    57         1           10     10.0      0.0    data_desc = mx.io.DataDesc(name='data', shape=(batch_size, seq_length), layout='NT')
    58         1            6      6.0      0.0    label_desc = mx.io.DataDesc(name='target', shape=(batch_size, seq_length), layout='NT')
    59         1            4      4.0      0.0    net = mx.mod.Module(symbol=loss,
    60         1            2      2.0      0.0                        data_names=['data'],
    61         1            2      2.0      0.0                        label_names=['target'],
    62         1          161    161.0      0.0                        context=mx.gpu())
    63         1       358986 358986.0      7.8    net.bind(data_shapes=[data_desc], label_shapes=[label_desc])
    64         1         7817   7817.0      0.2    net.init_params(initializer=mx.init.Xavier())
    65         1            3      3.0      0.0    net.init_optimizer(optimizer="adam",
    66         1            2      2.0      0.0                       optimizer_params={'learning_rate': 1E-3,
    67         1            2      2.0      0.0                                         'rescale_grad': 1.0},
    68         1          331    331.0      0.0                       kvstore=None)
    69                                           
    70                                             # We build another testing network that outputs the logits.
    71         1            4      4.0      0.0    test_net = mx.mod.Module(symbol=logits,
    72         1            3      3.0      0.0                             data_names=[data_desc.name],
    73         1            1      1.0      0.0                             label_names=None,
    74         1           96     96.0      0.0                             context=mx.gpu())
    75                                             # Setting the `shared_module` to ensure that the test network shares the same parameters and
    76                                             #  allocated memory of the training network
    77         1            3      3.0      0.0    test_net.bind(data_shapes=[data_desc],
    78         1            2      2.0      0.0                  label_shapes=None,
    79         1            2      2.0      0.0                  for_training=False,
    80         1            2      2.0      0.0                  grad_req='null',
    81         1          942    942.0      0.0                  shared_module=net)
    82                                           
    83         1            3      3.0      0.0    begin = time.time()
    84       101          209      2.1      0.0    for epoch in range(100):
    85       100          187      1.9      0.0        avg_cost = 0
    86       100          423      4.2      0.0        total_batch = int(math.ceil(dataX.shape[0] / batch_size))
    87       100         4101     41.0      0.1        shuffle_ind = np.random.permutation(np.arange(dataX.shape[0]))
    88       100         3158     31.6      0.1        dataX = dataX[shuffle_ind, :]
    89       100         1990     19.9      0.0        dataY = dataY[shuffle_ind]
    90      3300         8063      2.4      0.2        for i in range(total_batch):
    91                                                     # Slice the data batch and target batch.
    92                                                     # Note that we use np.take to ensure that the batch will be padded correctly.
    93      3200         6736      2.1      0.1            data_npy = np.take(dataX,
    94      3200        14218      4.4      0.3                               indices=np.arange(i * batch_size, (i+1) * batch_size),
    95      3200         5591      1.7      0.1                               axis=0,
    96      3200        28620      8.9      0.6                               mode="clip")
    97      3200         6309      2.0      0.1            target_npy = np.take(dataY,
    98      3200         8767      2.7      0.2                                 indices=np.arange(i * batch_size, (i + 1) * batch_size),
    99      3200         5474      1.7      0.1                                 axis=0,
   100      3200        15648      4.9      0.3                                 mode="clip")
   101      3200       248822     77.8      5.4            net.forward_backward(data_batch=mx.io.DataBatch(data=[nd.array(data_npy)],
   102      3200      1234960    385.9     26.9                                                            label=[nd.array(target_npy)]))
   103      3200      1210850    378.4     26.4            loss = net.get_outputs()[0].asscalar()
   104      3200        27548      8.6      0.6            avg_cost += loss / total_batch
   105      3200      1363940    426.2     29.7            net.update()
   106       100         2451     24.5      0.1        print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))
   107         1            4      4.0      0.0    print('Learning Finished!')
   108         1            3      3.0      0.0    end = time.time()
   109         1            6      6.0      0.0    print("Total Time Spent: %gs" %(end - begin))
```

**Comment by hunkim** [comment]
@kkweon Wow. Hello MXNET! However, do you think this is Keras or TF? An easy way to figure it out. Can you test it with torch backend? Or should we implement a TF version?

2~3 times are even not acceptable but 10 times?

Cheers,
Sung

**Comment by kkweon** [comment]
Wait a minute. Why did you enable Tensorboard?

**Comment by kkweon** [comment]
With the Theano backend, it's almost twice slower than the tensorflow backend.
I have a feeling this is a Keras thing. We should test it against Tensorflow, but I don't have time til next week.

**Comment by hunkim** [comment]
Thanks! It's not urgent. Should we report this to the Keras author? Mo
Kewn, do you want to talk to him?

Sung

**Comment by kkweon** [comment]
Well, I'd rather wait but you can try.
I'm not 100 certain at this moment, but I have a feeling this thing has to do with `Fused RNN`, which usually runs 10 times faster than the regular RNN cells by utilizing matrix operations.
Keras must be on regular RNN implementations not the fused one.

**Comment by sxjscience** [comment]
I tested the unfused version yesterday and it's still about 4 times faster than Keras + TF. Also on my computer the speed of TF backend is similar to Theano backend.... I decide to add another script MXNet RNN without 'FusedRNN' in the demo.

**Comment by sxjscience** [comment]
@hunkim I'll create a separate repo.

**Comment by sxjscience** [comment]
@hunkim @kkweon I've added the repo here https://github.com/sxjscience/aws-summit-2017-seoul . In fact, TF backend is slower than Theano :sweat_smile:

**Comment by hunkim** [comment]
Cool. Thanks!

**Pull request closed without merging**
